/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include "../../mbedutils/include/mbedutils/interfaces/assert_intf.hpp"

#include <CppUTestExt/MockSupport.h>

void mb::assert::on_assert_fail(const bool halt, const etl::string_view & msg)
{
    mock().actualCall("mb::assert::on_assert_fail").withBoolParameter("halt", halt).withParameterOfType("etl::string_view", "msg", &msg);
}

