/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include "../../mbedutils/include/mbedutils/drivers/memory/nvm/nor_flash_device.hpp"

#include <CppUTestExt/MockSupport.h>

mb::memory::Status mb::memory::nor::device::adesto_at25sfxxx_pend_event(const mb::memory::nor::DeviceConfig & cfg, const mb::memory::nor::Event event, const size_t timeout)
{
    return static_cast<mb::memory::Status>(mock().actualCall("mb::memory::nor::device::adesto_at25sfxxx_pend_event").withParameterOfType("mb::memory::nor::DeviceConfig", "cfg", &cfg).withIntParameter("event", static_cast<int>(event)).withUnsignedLongIntParameter("timeout", timeout).returnIntValue());
}

