/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include <CppUMockGen.hpp>

#include "../../mbedutils/include/mbedutils/interfaces/assert_intf.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace mb$ { namespace assert$ {
MockExpectedCall& on_assert_fail(CppUMockGen::Parameter<const bool> halt, CppUMockGen::Parameter<const etl::string_view &> msg);
MockExpectedCall& on_assert_fail(unsigned int __numCalls__, CppUMockGen::Parameter<const bool> halt, CppUMockGen::Parameter<const etl::string_view &> msg);
} } }

