/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include <CppUMockGen.hpp>

#include "../../mbedutils/include/mbedutils/drivers/system/atexit.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace mb$ { namespace system$ { namespace atexit$ {
MockExpectedCall& initialize();
MockExpectedCall& initialize(unsigned int __numCalls__);
} } } }

namespace expect { namespace mb$ { namespace system$ { namespace atexit$ {
MockExpectedCall& registerCallback(mb::system::atexit::Callback & callback, CppUMockGen::Parameter<uint32_t> priority, bool __return__);
MockExpectedCall& registerCallback(unsigned int __numCalls__, mb::system::atexit::Callback & callback, CppUMockGen::Parameter<uint32_t> priority, bool __return__);
} } } }

namespace expect { namespace mb$ { namespace system$ { namespace atexit$ {
MockExpectedCall& unregisterCallback(mb::system::atexit::Callback & callback, bool __return__);
MockExpectedCall& unregisterCallback(unsigned int __numCalls__, mb::system::atexit::Callback & callback, bool __return__);
} } } }

namespace expect { namespace mb$ { namespace system$ { namespace atexit$ {
MockExpectedCall& exit();
MockExpectedCall& exit(unsigned int __numCalls__);
} } } }

