/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include <CppUMockGen.hpp>

#include "../../mbedutils/include/mbedutils/interfaces/irq_intf.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace mb$ { namespace irq$ {
MockExpectedCall& in_isr(bool __return__);
MockExpectedCall& in_isr(unsigned int __numCalls__, bool __return__);
} } }

namespace expect { namespace mb$ { namespace irq$ {
MockExpectedCall& disable_interrupts();
MockExpectedCall& disable_interrupts(unsigned int __numCalls__);
} } }

namespace expect { namespace mb$ { namespace irq$ {
MockExpectedCall& enable_interrupts();
MockExpectedCall& enable_interrupts(unsigned int __numCalls__);
} } }

