/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 *
 * Generation options: -s c++20
 */

#include <CppUMockGen.hpp>

#include "../../mbedutils/include/mbedutils/drivers/memory/nvm/nor_flash_device.hpp"

#include <CppUTestExt/MockSupport.h>

namespace expect { namespace mb$ { namespace memory$ { namespace nor$ { namespace device$ {
MockExpectedCall& adesto_at25sfxxx_pend_event(CppUMockGen::Parameter<const mb::memory::nor::DeviceConfig &> cfg, CppUMockGen::Parameter<const mb::memory::nor::Event> event, CppUMockGen::Parameter<const size_t> timeout, mb::memory::Status __return__);
MockExpectedCall& adesto_at25sfxxx_pend_event(unsigned int __numCalls__, CppUMockGen::Parameter<const mb::memory::nor::DeviceConfig &> cfg, CppUMockGen::Parameter<const mb::memory::nor::Event> event, CppUMockGen::Parameter<const size_t> timeout, mb::memory::Status __return__);
} } } } }

